### ISSUE TITLE
Question about using another model

### ISSUE THREAD

**Issue by laxsas** [MLOPTPSU/FedTorch#12]
I want to train resnet model instead of  mlp one. 
How do I specify which model to use?

**Comment by mmkamani7** [comment]
You can change the name of the model in `run_mpi.py` for the specific dataset to `resnet`. Then you need to update the `model_params` dictionary with the appropriate ResNet parameters you need.

**Comment by laxsas** [comment]
Thank you for quick reply.
I tried what you said and it worked , I can train resnet model.
Thank you!!!
