### ISSUE TITLE
About alpha_update in fedtorch/comms/utils/flow_utils.py

### ISSUE THREAD

**Issue by Emiem2017** [MLOPTPSU/FedTorch#15]
![image](https://user-images.githubusercontent.com/31511814/229136365-60c80f54-4edf-43b7-b8f0-b4ea5cc655fe.png)
I found the code in github has something else compared with paper. Like the code in red box, where does the 0.02 come from?
The formula （10）does not mentioned that item.
![image](https://user-images.githubusercontent.com/31511814/229136447-ef4e09ae-848e-4898-88e5-e6a98b2a6c59.png)

**Comment by mmkamani7** [comment]
Thanks for mentioning this. This is the momentum for updating alpha to make it more stable.

**Comment by Emiem2017** [comment]
Thank you so much!!!
