### ISSUE TITLE
No basic auth credentials

### ISSUE THREAD

**Issue by Sybil-Huang** [MLOPTPSU/FedTorch#3]
I read your paper and am interested in your proposed method.  It is really nice of you to share such a helpful and clear repo. I pulled one of the images built with CUDA 10.2 and OpenMPI 4.0.1 with CUDA support and PyTorch 1.6.0, using the following command:
$ docker pull docker.pkg.github.com/mloptpsu/fedtorch/fedtorch:cuda10.2-mpi

However it reported an error "Error response from daemon: Head https://docker.pkg.github.com/v2/mloptpsu/fedtorch/fedtorch/manifests/cuda10.2-mpi: no basic auth credentials".  
How can I solve this error?

**Comment by mmkamani7** [comment]
Hi. Thanks for your interest. That is probably because the Github login information is not stored in your local computer. You can also pull the docker container from the docker hub using:
```cli
docker pull mmkamani/pytorch-cuda-mpi:v1.6.0
```
Please let me know if that does not solve your problem.

**Comment by mmkamani7** [comment]
Use external docker image.
