### ISSUE TITLE
Could you release the code in "Federated Learning with Compression: Unified Analysis and Sharp Guarantees"?

### ISSUE THREAD

**Issue by Dzhange** [MLOPTPSU/FedTorch#7]
Hi,

I just read the paper of "Federated Learning with Compression: Unified Analysis and Sharp Guarantees", it looks very interesting
While searching for the code I was directed to this repo, however, I didn't found the implementation of FedCOM, so I would like to ask if you would release it?

Thanks!

**Comment by mmkamani7** [comment]
Hi, thanks for your interest. The code is in the repo. For FedCOM, you can use the fedavg algorithm with option `-q` to add quantization to it. The script would be something like this:

```bash
python run_mpi.py -f -ft fedavg -n 10 -d mnist -lg 0.1 -b 50 -c 20 -k 1.0 -fs local_step -l 10 -r 2 -q
```
