### ISSUE TITLE
Image fail to pull?

### ISSUE THREAD

**Issue by qiu-wanyong** [MLOPTPSU/FedTorch#9]
Does FedTorch's image always fail to pull?

Docker pull:
“docker pull docker.pkg.github.com/mloptpsu/fedtorch/fedtorch:cuda10.2-mpi”

**Comment by sandeepnmenon** [comment]
Its not pulling for me as well. Getting the following error
```
$ sudo docker pull docker.pkg.github.com/mloptpsu/fedtorch/fedtorch:cuda10.2-mpi
Error response from daemon: Head https://docker.pkg.github.com/v2/mloptpsu/fedtorch/fedtorch/manifests/cuda10.2-mpi: no basic auth credentials

```

**Comment by mmkamani7** [comment]
Hi. Thanks for your interest. That is probably because the Github login information is not stored on your local computer. You can also pull the docker container from the docker hub using:

`docker pull mmkamani/pytorch-cuda-mpi:v1.6.0`

Please let me know if that does not solve your problem.
